---
name: TAP-Formatter-HTML
version: 0.04
author:
  - 'Steve Purkis <spurkis@cpan.org>'
abstract: TAP Test Harness output delegate for html output
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  TAP::Parser: 3.10
  Template: 2.14
  URI: 1.35
  accessors: 0.02
  perl: 5.6.0
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
provides:
  TAP::Formatter::HTML:
    file: lib/TAP/Formatter/HTML.pm
    version: 0.04
  TAP::Formatter::HTML::Session:
    file: lib/TAP/Formatter/HTML/Session.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
