---
name: TAP-Formatter-HTML
version: 0.09
author:
  - 'Steve Purkis <spurkis@cpan.org>'
abstract: TAP Test Harness output delegate for html output
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
requires:
  File::Temp: 0.17
  TAP::Parser: 3.10
  Template: 2.14
  Test::Harness: 3.17
  URI: 1.35
  accessors: 0.02
  perl: v5.6.0
configure_requires:
  Module::Build: 0.35
provides:
  App::Prove::Plugin::HTML:
    file: lib/App/Prove/Plugin/HTML.pm
    version: 0.09
  TAP::Formatter::HTML:
    file: lib/TAP/Formatter/HTML.pm
    version: 0.09
  TAP::Formatter::HTML::Session:
    file: lib/TAP/Formatter/HTML/Session.pm
    version: 0.09
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
