---
abstract: 'TAP Test Harness output delegate for html output'
author:
  - 'Steve Purkis <spurkis@cpan.org>'
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Formatter-HTML
provides:
  App::Prove::Plugin::HTML:
    file: lib/App/Prove/Plugin/HTML.pm
    version: 0.11
  TAP::Formatter::HTML:
    file: lib/TAP/Formatter/HTML.pm
    version: 0.11
  TAP::Formatter::HTML::Session:
    file: lib/TAP/Formatter/HTML/Session.pm
    version: 0.11
requires:
  File::Temp: 0.17
  TAP::Parser: 3.10
  Template: 2.14
  Test::Harness: 3.17
  URI: 1.35
  accessors: 0.02
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
